/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// RulesetDto Rules for an inbox or phone number. Rulesets can be used to block, allow, filter, or bounce emails or SMS when sending or receiving.
type RulesetDto struct {
	Id string `json:"id"`
	InboxId *string `json:"inboxId,omitempty"`
	PhoneId *string `json:"phoneId,omitempty"`
	Scope string `json:"scope"`
	Action string `json:"action"`
	Target string `json:"target"`
	Handler string `json:"handler"`
	CreatedAt time.Time `json:"createdAt"`
}
