/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// DomainPreview Preview object for domain entity
type DomainPreview struct {
	Id string `json:"id,omitempty"`
	Domain string `json:"domain,omitempty"`
	CatchAllInboxId string `json:"catchAllInboxId,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Type of domain. Dictates type of inbox that can be created with domain. HTTP means inboxes are processed using SES while SMTP inboxes use a custom SMTP mail server. SMTP does not support sending so use HTTP for sending emails.
	DomainType string `json:"domainType,omitempty"`
	Verified bool `json:"verified,omitempty"`
}
