/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * API version: 6.5.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// DomainDto Domain plus verification records and status
type DomainDto struct {
	CreatedAt time.Time `json:"createdAt"`
	Domain string `json:"domain"`
	Id string `json:"id"`
	IsVerified bool `json:"isVerified"`
	UpdatedAt time.Time `json:"updatedAt"`
	UserId string `json:"userId"`
	VerificationToken string `json:"verificationToken"`
}
