/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// WebhookProjection Representation of a webhook
type WebhookProjection struct {
	Url string `json:"url"`
	Password string `json:"password,omitempty"`
	Username string `json:"username,omitempty"`
	UserId string `json:"userId"`
	InboxId string `json:"inboxId,omitempty"`
	EventName string `json:"eventName,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`
	HealthStatus string `json:"healthStatus,omitempty"`
	PhoneNumberId string `json:"phoneNumberId,omitempty"`
	Name string `json:"name,omitempty"`
	Id string `json:"id"`
}
