/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
// DeliverabilityExpectation Single expectation to evaluate against each selected entity
type DeliverabilityExpectation struct {
	// Optional label for this expectation
	Name *string `json:"name,omitempty"`
	// Minimum number of matching messages required for this expectation to pass
	MinCount int64 `json:"minCount"`
	// Optional sender filter. Matching is case-insensitive contains against inbound sender/from values.
	From *string `json:"from,omitempty"`
	// Optional recipient filter. Matching is case-insensitive contains against recipient/to values.
	To *string `json:"to,omitempty"`
	// Optional subject filter for INBOX scope tests. Ignored for PHONE scope tests.
	Subject *string `json:"subject,omitempty"`
}
