/*
 * MailSlurp API
 *
 * For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
 *
 * API version: 0.0.1-alpha
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mailslurp

// Analysis of email
type EmailAnalysis struct {
	DkimVerdict string `json:"dkimVerdict,omitempty"`
	DmarcVerdict string `json:"dmarcVerdict,omitempty"`
	SpamVerdict string `json:"spamVerdict,omitempty"`
	SpfVerdict string `json:"spfVerdict,omitempty"`
	VirusVerdict string `json:"virusVerdict,omitempty"`
}
