/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// TemplateDto Email template
type TemplateDto struct {
	// ID of template
	Id string `json:"id"`
	// Template name
	Name string `json:"name"`
	// Variables available in template that can be replaced with values
	Variables []TemplateVariable `json:"variables"`
	// Content of the template
	Content string `json:"content"`
	// Created at time
	CreatedAt time.Time `json:"createdAt"`
}
