/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
// CreateDevicePreviewFeedbackOptions struct for CreateDevicePreviewFeedbackOptions
type CreateDevicePreviewFeedbackOptions struct {
	Source string `json:"source"`
	Category string `json:"category"`
	Status string `json:"status,omitempty"`
	Rating int32 `json:"rating,omitempty"`
	RunId string `json:"runId,omitempty"`
	TargetId string `json:"targetId,omitempty"`
	ScreenshotId string `json:"screenshotId,omitempty"`
	Provider string `json:"provider,omitempty"`
	Title string `json:"title,omitempty"`
	Comment string `json:"comment,omitempty"`
	InternalNote string `json:"internalNote,omitempty"`
	SessionId string `json:"sessionId,omitempty"`
	LiveViewUrl string `json:"liveViewUrl,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}
