/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// AuditLogEventDto struct for AuditLogEventDto
type AuditLogEventDto struct {
	TenantId string `json:"tenantId"`
	Dt string `json:"dt,omitempty"`
	EventId string `json:"eventId"`
	EventTs time.Time `json:"eventTs"`
	Action string `json:"action"`
	UserId string `json:"userId,omitempty"`
	ActorUserId string `json:"actorUserId,omitempty"`
	TargetUserId string `json:"targetUserId,omitempty"`
	ResourceType string `json:"resourceType,omitempty"`
	ResourceId string `json:"resourceId,omitempty"`
	Outcome string `json:"outcome,omitempty"`
	RequestId string `json:"requestId,omitempty"`
	IpAddress string `json:"ipAddress,omitempty"`
	MetadataJson string `json:"metadataJson,omitempty"`
}
