/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
// ExtractCodesOptions Options for extracting verification codes from email or SMS content. Use method to control extraction strategy and allowFallback to control strictness.
type ExtractCodesOptions struct {
	// Extraction strategy for verification codes. Unsupported strategies may fall back when allowFallback is true.
	Method *string `json:"method,omitempty"`
	// Allow fallback to deterministic pattern extraction when the selected method is unavailable.
	AllowFallback bool `json:"allowFallback,omitempty"`
	// Minimum code length to consider. Typical OTP values are between 4 and 8 characters.
	MinLength int32 `json:"minLength,omitempty"`
	// Maximum code length to consider.
	MaxLength int32 `json:"maxLength,omitempty"`
	// Maximum number of code candidates to return. Best candidate is also returned separately.
	MaxCandidates int32 `json:"maxCandidates,omitempty"`
	// Optional custom regex patterns for code extraction. Each pattern should have either one capture group for the code or match the full code directly.
	CustomPatterns *[]string `json:"customPatterns,omitempty"`
}
