/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// InboxForwarderEventProjection Inbox forwarder event
type InboxForwarderEventProjection struct {
	CreatedAt time.Time `json:"createdAt"`
	UserId *string `json:"userId,omitempty"`
	EmailId *string `json:"emailId,omitempty"`
	InboxId *string `json:"inboxId,omitempty"`
	SentId *string `json:"sentId,omitempty"`
	ForwarderId *string `json:"forwarderId,omitempty"`
	Message *string `json:"message,omitempty"`
	Id *string `json:"id,omitempty"`
	Status *string `json:"status,omitempty"`
}
