/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * API version: d1659dc1567a5b62f65d0612107a50aace03e085
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mailslurp
import (
	"time"
)
// UpdateInboxOptions Options for updating inbox properties
type UpdateInboxOptions struct {
	// Optional description of an inbox for labelling purposes
	Description string `json:"description,omitempty"`
	// When, if ever, will the inbox expire and be deleted. If null then this inbox is permanent and the emails in it won't be deleted.
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	// Is the inbox favourited
	Favourite bool `json:"favourite,omitempty"`
	// Optional name of the inbox. Displayed in the dashboard for easier search
	Name string `json:"name,omitempty"`
	// Tags that inbox has been tagged with
	Tags []string `json:"tags,omitempty"`
}
