/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * API version: 6.5.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// OrganizationInboxProjection struct for OrganizationInboxProjection
type OrganizationInboxProjection struct {
	// When the inbox was created. Time stamps are in ISO DateTime Format `yyyy-MM-dd'T'HH:mm:ss.SSSXXX` e.g. `2000-10-31T01:30:00.000-05:00`.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// The inbox's email address. Inbox projections and previews may not include the email address. To view the email address fetch the inbox entity directly. Send an email to this address and the inbox will receive and store it for you. Note the email address in MailSlurp match characters exactly and are case sensitive so `+123` additions are considered different addresses. To retrieve the email use the Inbox and Email Controller endpoints with the inbox ID.
	EmailAddress string `json:"emailAddress,omitempty"`
	// Is the inbox favorited. Favouriting inboxes is typically done in the dashboard for quick access or filtering
	Favourite bool `json:"favourite,omitempty"`
	// ID of the inbox. The ID is a UUID-V4 format string. Use the inboxId for calls to Inbox and Email Controller endpoints. See the emailAddress property for the email address or the inbox. To get emails in an inbox use the WaitFor and Inbox Controller methods `waitForLatestEmail` and `getEmails` methods respectively. Inboxes can be used with aliases to forward emails automatically.
	Id string `json:"id,omitempty"`
	// Name of the inbox. Displayed in the dashboard for easier search
	Name string `json:"name,omitempty"`
	// Is the inbox readOnly for the caller. Read only means can not be deleted or modified.
	ReadOnly bool `json:"readOnly,omitempty"`
	// Tags that inbox has been tagged with. Tags can be added to inboxes to group different inboxes within an account. You can also search for inboxes by tag in the dashboard UI.
	Tags []string `json:"tags,omitempty"`
	// Does inbox permit team access for organization team members. If so team users can use inbox and emails associated with it.
	TeamAccess bool `json:"teamAccess,omitempty"`
}
