/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// DeliveryStatusDto struct for DeliveryStatusDto
type DeliveryStatusDto struct {
	Id string `json:"id"`
	UserId string `json:"userId"`
	SentId string `json:"sentId,omitempty"`
	RemoteMtaIp string `json:"remoteMtaIp,omitempty"`
	InboxId string `json:"inboxId,omitempty"`
	ReportingMta string `json:"reportingMta,omitempty"`
	Recipients []string `json:"recipients,omitempty"`
	SmtpResponse string `json:"smtpResponse,omitempty"`
	SmtpStatusCode int32 `json:"smtpStatusCode,omitempty"`
	ProcessingTimeMillis int64 `json:"processingTimeMillis,omitempty"`
	Received time.Time `json:"received,omitempty"`
	Subject string `json:"subject,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
