/*
 * MailSlurp API
 *
 * For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).
 *
 * API version: 0.0.1-alpha
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mailslurp

type PageEmailProjection struct {
	Content []EmailProjection `json:"content,omitempty"`
	First bool `json:"first,omitempty"`
	Last bool `json:"last,omitempty"`
	Number int32 `json:"number,omitempty"`
	NumberOfElements int32 `json:"numberOfElements,omitempty"`
	Pageable Pageable `json:"pageable,omitempty"`
	Size int32 `json:"size,omitempty"`
	Sort Sort `json:"sort,omitempty"`
	TotalElements int64 `json:"totalElements,omitempty"`
	TotalPages int32 `json:"totalPages,omitempty"`
}
