/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// SmsPreview struct for SmsPreview
type SmsPreview struct {
	Id string `json:"id"`
	UserId string `json:"userId"`
	// TXT message content
	Body string `json:"body"`
	// ID of the phone number that received this SMS
	PhoneNumber string `json:"phoneNumber"`
	// Sender number
	FromNumber string `json:"fromNumber"`
	// Is the message read or unread
	Read bool `json:"read"`
	CreatedAt time.Time `json:"createdAt"`
}
