/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// DeliverabilityAnalyticsRunDto Run-level metrics for analytics tables
type DeliverabilityAnalyticsRunDto struct {
	Id string `json:"id"`
	Name *string `json:"name,omitempty"`
	Scope string `json:"scope"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	StartAt time.Time `json:"startAt"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	TotalEntities int64 `json:"totalEntities"`
	MatchedEntities int64 `json:"matchedEntities"`
	UnmatchedEntities int64 `json:"unmatchedEntities"`
	CompletionPercentage float64 `json:"completionPercentage"`
	SuccessThresholdPercent *float64 `json:"successThresholdPercent,omitempty"`
	ThresholdStatus string `json:"thresholdStatus"`
}
