/*
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * API version: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MailSlurpClient
import (
	"time"
)
// WebhookEmailReadPayload EMAIL_READ webhook payload. Sent to your webhook url endpoint via HTTP POST when an email is read. This happens when an email is requested in full from the API or a user views the email in the dashboard.
type WebhookEmailReadPayload struct {
	// Idempotent message ID. Store this ID locally or in a database to prevent message duplication.
	MessageId string `json:"messageId"`
	// ID of webhook entity being triggered
	WebhookId string `json:"webhookId"`
	// Name of the event type webhook is being triggered for.
	EventName string `json:"eventName"`
	// Name of the webhook being triggered
	WebhookName string `json:"webhookName,omitempty"`
	// ID of the email that was received. Use this ID for fetching the email with the `EmailController`.
	EmailId string `json:"emailId"`
	// Id of the inbox that received an email
	InboxId string `json:"inboxId"`
	// Is the email read
	EmailIsRead bool `json:"emailIsRead"`
	// Date time of event creation
	CreatedAt time.Time `json:"createdAt"`
}
